import Head from 'next/head'
import Welcome from "@/components/Welcome/Welcome";
import AboutUs from "@/components/AboutUs/AboutUs";
export default function HomePage() {
  return (
    <>
      <Head>
        <title>Home | WishLister</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Welcome/>
        <AboutUs/>
      </main>
    </>
  )
}
